// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const bulkCreateAssessments = `-- name: BulkCreateAssessments :exec
INSERT INTO assessments (
    id, category
) 
SELECT 
    unnest($1::text[]), 
    unnest($2::text[])
`

type BulkCreateAssessmentsParams struct {
	Ids        []string
	Categories []string
}

func (q *Queries) BulkCreateAssessments(ctx context.Context, arg BulkCreateAssessmentsParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateAssessments, pq.Array(arg.Ids), pq.Array(arg.Categories))
	return err
}

const bulkCreateChoices = `-- name: BulkCreateChoices :exec
INSERT INTO choices (
    id, question_id, text, is_correct
) 
SELECT 
    unnest($1::text[]), 
    unnest($2::text[]), 
    unnest($3::text[]), 
    unnest($4::boolean[])
`

type BulkCreateChoicesParams struct {
	Ids         []string
	QuestionIds []string
	Texts       []string
	IsCorrects  []bool
}

func (q *Queries) BulkCreateChoices(ctx context.Context, arg BulkCreateChoicesParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateChoices,
		pq.Array(arg.Ids),
		pq.Array(arg.QuestionIds),
		pq.Array(arg.Texts),
		pq.Array(arg.IsCorrects),
	)
	return err
}

const bulkCreateQuestions = `-- name: BulkCreateQuestions :exec
INSERT INTO questions (
    id, assessment_id, text, image_url, type, feedback_correct, feedback_incorrect
) 
SELECT 
    unnest($1::text[]), 
    unnest($2::text[]), 
    unnest($3::text[]), 
    unnest($4::text[]), 
    unnest($5::text[]), 
    unnest($6::text[]), 
    unnest($7::text[])
`

type BulkCreateQuestionsParams struct {
	Ids                []string
	AssessmentIds      []string
	Texts              []string
	ImageUrls          []string
	Types              []string
	FeedbacksCorrect   []string
	FeedbacksIncorrect []string
}

func (q *Queries) BulkCreateQuestions(ctx context.Context, arg BulkCreateQuestionsParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateQuestions,
		pq.Array(arg.Ids),
		pq.Array(arg.AssessmentIds),
		pq.Array(arg.Texts),
		pq.Array(arg.ImageUrls),
		pq.Array(arg.Types),
		pq.Array(arg.FeedbacksCorrect),
		pq.Array(arg.FeedbacksIncorrect),
	)
	return err
}

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (
    id, category
) VALUES (
    $1, $2
) RETURNING id, category
`

type CreateAssessmentParams struct {
	ID       string
	Category string
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, createAssessment, arg.ID, arg.Category)
	var i Assessment
	err := row.Scan(&i.ID, &i.Category)
	return i, err
}

const createChoice = `-- name: CreateChoice :one
INSERT INTO choices (
    id, question_id, text, is_correct
) VALUES (
    $1, $2, $3, $4
) RETURNING id, question_id, text, is_correct
`

type CreateChoiceParams struct {
	ID         string
	QuestionID string
	Text       string
	IsCorrect  bool
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error) {
	row := q.db.QueryRowContext(ctx, createChoice,
		arg.ID,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
	)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    id, assessment_id, text, image_url, type, feedback_correct, feedback_incorrect
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, assessment_id, text, image_url, type, feedback_correct, feedback_incorrect
`

type CreateQuestionParams struct {
	ID                string
	AssessmentID      string
	Text              string
	ImageUrl          sql.NullString
	Type              string
	FeedbackCorrect   string
	FeedbackIncorrect string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.ID,
		arg.AssessmentID,
		arg.Text,
		arg.ImageUrl,
		arg.Type,
		arg.FeedbackCorrect,
		arg.FeedbackIncorrect,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.Text,
		&i.ImageUrl,
		&i.Type,
		&i.FeedbackCorrect,
		&i.FeedbackIncorrect,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM assessments WHERE id = $1
`

func (q *Queries) DeleteAssessment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAssessment, id)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, category FROM assessments WHERE category = $1 AND id = $2 LIMIT 1
`

type GetAssessmentParams struct {
	Category string
	ID       string
}

func (q *Queries) GetAssessment(ctx context.Context, arg GetAssessmentParams) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, getAssessment, arg.Category, arg.ID)
	var i Assessment
	err := row.Scan(&i.ID, &i.Category)
	return i, err
}

const getAssessmentById = `-- name: GetAssessmentById :one
SELECT id, category FROM assessments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAssessmentById(ctx context.Context, id string) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, getAssessmentById, id)
	var i Assessment
	err := row.Scan(&i.ID, &i.Category)
	return i, err
}

const getChoicesByQuestionIds = `-- name: GetChoicesByQuestionIds :many
SELECT id, question_id, text, is_correct FROM choices WHERE question_id = ANY($1::text[]) ORDER BY question_id, id ASC
`

func (q *Queries) GetChoicesByQuestionIds(ctx context.Context, questionIds []string) ([]Choice, error) {
	rows, err := q.db.QueryContext(ctx, getChoicesByQuestionIds, pq.Array(questionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByAssessmentId = `-- name: GetQuestionsByAssessmentId :many
SELECT id, assessment_id, text, image_url, type, feedback_correct, feedback_incorrect FROM questions WHERE assessment_id = $1 ORDER BY id ASC
`

func (q *Queries) GetQuestionsByAssessmentId(ctx context.Context, assessmentID string) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsByAssessmentId, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.Text,
			&i.ImageUrl,
			&i.Type,
			&i.FeedbackCorrect,
			&i.FeedbackIncorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessments = `-- name: ListAssessments :many
SELECT id, category FROM assessments ORDER BY category ASC, id ASC LIMIT $1
`

func (q *Queries) ListAssessments(ctx context.Context, limit int32) ([]Assessment, error) {
	rows, err := q.db.QueryContext(ctx, listAssessments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(&i.ID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssessment = `-- name: UpdateAssessment :one
UPDATE assessments SET category = $2 WHERE id = $1 RETURNING id, category
`

type UpdateAssessmentParams struct {
	ID       string
	Category string
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, updateAssessment, arg.ID, arg.Category)
	var i Assessment
	err := row.Scan(&i.ID, &i.Category)
	return i, err
}
