// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lesson_progress.sql

package database

import (
	"context"
)

const createLessonProgressEntry = `-- name: CreateLessonProgressEntry :one
INSERT INTO lesson_progress(user_id, lesson_slug)
VALUES (
    (SELECT user_id FROM users WHERE clerk_id = $1),
    $2
)
RETURNING user_id, lesson_slug, completed_at
`

type CreateLessonProgressEntryParams struct {
	ClerkID    string
	LessonSlug string
}

func (q *Queries) CreateLessonProgressEntry(ctx context.Context, arg CreateLessonProgressEntryParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, createLessonProgressEntry, arg.ClerkID, arg.LessonSlug)
	var i LessonProgress
	err := row.Scan(&i.UserID, &i.LessonSlug, &i.CompletedAt)
	return i, err
}

const deleteLessonProgress = `-- name: DeleteLessonProgress :one
DELETE FROM lesson_progress
WHERE
    user_id = (SELECT user_id FROM users WHERE clerk_id = $1)
    AND lesson_slug = $2
RETURNING user_id, lesson_slug, completed_at
`

type DeleteLessonProgressParams struct {
	ClerkID    string
	LessonSlug string
}

func (q *Queries) DeleteLessonProgress(ctx context.Context, arg DeleteLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, deleteLessonProgress, arg.ClerkID, arg.LessonSlug)
	var i LessonProgress
	err := row.Scan(&i.UserID, &i.LessonSlug, &i.CompletedAt)
	return i, err
}
