// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson_progress.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLessonProgressEntry = `-- name: CreateLessonProgressEntry :one
INSERT INTO lesson_progress(user_id, lesson_category, lesson_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, lesson_category, lesson_id) 
DO UPDATE SET completed_at = now()
RETURNING user_id, lesson_category, lesson_id, completed_at
`

type CreateLessonProgressEntryParams struct {
	UserID         uuid.UUID
	LessonCategory string
	LessonID       string
}

func (q *Queries) CreateLessonProgressEntry(ctx context.Context, arg CreateLessonProgressEntryParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, createLessonProgressEntry, arg.UserID, arg.LessonCategory, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.UserID,
		&i.LessonCategory,
		&i.LessonID,
		&i.CompletedAt,
	)
	return i, err
}

const deleteAllLessonProgress = `-- name: DeleteAllLessonProgress :exec
DELETE FROM lesson_progress
WHERE user_id = $1
`

func (q *Queries) DeleteAllLessonProgress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllLessonProgress, userID)
	return err
}

const deleteCategoryLessonProgress = `-- name: DeleteCategoryLessonProgress :exec
DELETE FROM lesson_progress
WHERE user_id = $1
  AND lesson_category = $2
`

type DeleteCategoryLessonProgressParams struct {
	UserID         uuid.UUID
	LessonCategory string
}

func (q *Queries) DeleteCategoryLessonProgress(ctx context.Context, arg DeleteCategoryLessonProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryLessonProgress, arg.UserID, arg.LessonCategory)
	return err
}

const deleteLessonProgress = `-- name: DeleteLessonProgress :one
DELETE FROM lesson_progress
WHERE user_id = $1 
  AND lesson_category = $2
  AND lesson_id = $3
RETURNING user_id, lesson_category, lesson_id, completed_at
`

type DeleteLessonProgressParams struct {
	UserID         uuid.UUID
	LessonCategory string
	LessonID       string
}

func (q *Queries) DeleteLessonProgress(ctx context.Context, arg DeleteLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, deleteLessonProgress, arg.UserID, arg.LessonCategory, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.UserID,
		&i.LessonCategory,
		&i.LessonID,
		&i.CompletedAt,
	)
	return i, err
}

const getAllLessonProgressByCategory = `-- name: GetAllLessonProgressByCategory :many
SELECT user_id, lesson_category, lesson_id, completed_at FROM lesson_progress
WHERE user_id = $1 
  AND lesson_category = $2
`

type GetAllLessonProgressByCategoryParams struct {
	UserID         uuid.UUID
	LessonCategory string
}

func (q *Queries) GetAllLessonProgressByCategory(ctx context.Context, arg GetAllLessonProgressByCategoryParams) ([]LessonProgress, error) {
	rows, err := q.db.QueryContext(ctx, getAllLessonProgressByCategory, arg.UserID, arg.LessonCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonProgress
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.UserID,
			&i.LessonCategory,
			&i.LessonID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLessonProgressByUser = `-- name: GetAllLessonProgressByUser :many
SELECT user_id, lesson_category, lesson_id, completed_at FROM lesson_progress
WHERE user_id = $1
`

func (q *Queries) GetAllLessonProgressByUser(ctx context.Context, userID uuid.UUID) ([]LessonProgress, error) {
	rows, err := q.db.QueryContext(ctx, getAllLessonProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonProgress
	for rows.Next() {
		var i LessonProgress
		if err := rows.Scan(
			&i.UserID,
			&i.LessonCategory,
			&i.LessonID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonProgressByID = `-- name: GetLessonProgressByID :one
SELECT user_id, lesson_category, lesson_id, completed_at FROM lesson_progress
WHERE user_id = $1 
  AND lesson_category = $2
  AND lesson_id = $3
`

type GetLessonProgressByIDParams struct {
	UserID         uuid.UUID
	LessonCategory string
	LessonID       string
}

func (q *Queries) GetLessonProgressByID(ctx context.Context, arg GetLessonProgressByIDParams) (LessonProgress, error) {
	row := q.db.QueryRowContext(ctx, getLessonProgressByID, arg.UserID, arg.LessonCategory, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.UserID,
		&i.LessonCategory,
		&i.LessonID,
		&i.CompletedAt,
	)
	return i, err
}
