// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (category_id, slug, title, content, order_index)
VALUES ($1, $2, $3, $4, $5)
RETURNING lesson_id, category_id, slug, title, content, order_index, created_at, updated_at
`

type CreateLessonParams struct {
	CategoryID uuid.UUID
	Slug       string
	Title      string
	Content    string
	OrderIndex int32
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, createLesson,
		arg.CategoryID,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.OrderIndex,
	)
	var i Lesson
	err := row.Scan(
		&i.LessonID,
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLessonCategory = `-- name: CreateLessonCategory :one
INSERT INTO lesson_categories (slug, title, description, order_index)
VALUES ($1, $2, $3, $4)
RETURNING category_id, slug, title, description, order_index, created_at, updated_at
`

type CreateLessonCategoryParams struct {
	Slug        string
	Title       string
	Description sql.NullString
	OrderIndex  int32
}

func (q *Queries) CreateLessonCategory(ctx context.Context, arg CreateLessonCategoryParams) (LessonCategory, error) {
	row := q.db.QueryRowContext(ctx, createLessonCategory,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
	)
	var i LessonCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE lesson_id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, lessonID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLesson, lessonID)
	return err
}

const deleteLessonCategory = `-- name: DeleteLessonCategory :exec
DELETE FROM lesson_categories WHERE category_id = $1
`

func (q *Queries) DeleteLessonCategory(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLessonCategory, categoryID)
	return err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT lesson_id, category_id, slug, title, content, order_index, created_at, updated_at FROM lessons WHERE lesson_id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, lessonID uuid.UUID) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonByID, lessonID)
	var i Lesson
	err := row.Scan(
		&i.LessonID,
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonBySlug = `-- name: GetLessonBySlug :one
SELECT l.lesson_id, l.category_id, l.slug, l.title, l.content, l.order_index, l.created_at, l.updated_at FROM lessons l
JOIN lesson_categories lc ON l.category_id = lc.category_id
WHERE lc.slug = $1 AND l.slug = $2
`

type GetLessonBySlugParams struct {
	Slug   string
	Slug_2 string
}

func (q *Queries) GetLessonBySlug(ctx context.Context, arg GetLessonBySlugParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLessonBySlug, arg.Slug, arg.Slug_2)
	var i Lesson
	err := row.Scan(
		&i.LessonID,
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonCategories = `-- name: GetLessonCategories :many
SELECT lc.category_id, lc.slug, lc.title, lc.description, lc.order_index, lc.created_at, lc.updated_at, COUNT(l.lesson_id) as lesson_count
FROM lesson_categories lc
LEFT JOIN lessons l ON lc.category_id = l.category_id
GROUP BY lc.category_id
ORDER BY lc.order_index
`

type GetLessonCategoriesRow struct {
	CategoryID  uuid.UUID
	Slug        string
	Title       string
	Description sql.NullString
	OrderIndex  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LessonCount int64
}

func (q *Queries) GetLessonCategories(ctx context.Context) ([]GetLessonCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonCategoriesRow
	for rows.Next() {
		var i GetLessonCategoriesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonCategoryBySlug = `-- name: GetLessonCategoryBySlug :one
SELECT category_id, slug, title, description, order_index, created_at, updated_at FROM lesson_categories WHERE slug = $1
`

func (q *Queries) GetLessonCategoryBySlug(ctx context.Context, slug string) (LessonCategory, error) {
	row := q.db.QueryRowContext(ctx, getLessonCategoryBySlug, slug)
	var i LessonCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonsByCategorySlug = `-- name: GetLessonsByCategorySlug :many
SELECT l.lesson_id, l.category_id, l.slug, l.title, l.content, l.order_index, l.created_at, l.updated_at FROM lessons l
JOIN lesson_categories lc ON l.category_id = lc.category_id
WHERE lc.slug = $1
ORDER BY l.order_index
`

func (q *Queries) GetLessonsByCategorySlug(ctx context.Context, slug string) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsByCategorySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.LessonID,
			&i.CategoryID,
			&i.Slug,
			&i.Title,
			&i.Content,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons
SET title = $2, content = $3, order_index = $4, updated_at = now()
WHERE lesson_id = $1
RETURNING lesson_id, category_id, slug, title, content, order_index, created_at, updated_at
`

type UpdateLessonParams struct {
	LessonID   uuid.UUID
	Title      string
	Content    string
	OrderIndex int32
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, updateLesson,
		arg.LessonID,
		arg.Title,
		arg.Content,
		arg.OrderIndex,
	)
	var i Lesson
	err := row.Scan(
		&i.LessonID,
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonCategory = `-- name: UpdateLessonCategory :one
UPDATE lesson_categories
SET title = $2, slug = $3, description = $4, order_index = $5, updated_at = now()
WHERE category_id = $1
RETURNING category_id, slug, title, description, order_index, created_at, updated_at
`

type UpdateLessonCategoryParams struct {
	CategoryID  uuid.UUID
	Title       string
	Slug        string
	Description sql.NullString
	OrderIndex  int32
}

func (q *Queries) UpdateLessonCategory(ctx context.Context, arg UpdateLessonCategoryParams) (LessonCategory, error) {
	row := q.db.QueryRowContext(ctx, updateLessonCategory,
		arg.CategoryID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.OrderIndex,
	)
	var i LessonCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
