// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Course struct {
	CourseID   uuid.UUID
	CourseName string
}

type LessonProgress struct {
	UserID         uuid.UUID
	LessonCategory string
	LessonID       string
	CompletedAt    time.Time
}

type QuizResult struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	QuizCategory string
	QuizID       string
	Score        int32
	TotalItems   int32
	TakenAt      time.Time
}

type SimulatorProgress struct {
	UserID            uuid.UUID
	SimulatorCategory string
	Path              string
	IsCompleted       bool
	UpdatedAt         sql.NullTime
}

type User struct {
	UserID     uuid.UUID
	ClerkID    string
	CourseID   uuid.NullUUID
	FirstName  string
	MiddleName sql.NullString
	LastName   string
	Email      string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	BlockID    sql.NullString
}
