// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question_stats.sql

package database

import (
	"context"
)

const getQuestionStats = `-- name: GetQuestionStats :one
SELECT question_id, correct, mistakes FROM question_stats WHERE question_id = $1
`

func (q *Queries) GetQuestionStats(ctx context.Context, questionID string) (QuestionStat, error) {
	row := q.db.QueryRowContext(ctx, getQuestionStats, questionID)
	var i QuestionStat
	err := row.Scan(&i.QuestionID, &i.Correct, &i.Mistakes)
	return i, err
}

const listQuestionStats = `-- name: ListQuestionStats :many
SELECT question_id, correct, mistakes FROM question_stats
`

func (q *Queries) ListQuestionStats(ctx context.Context) ([]QuestionStat, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionStat
	for rows.Next() {
		var i QuestionStat
		if err := rows.Scan(&i.QuestionID, &i.Correct, &i.Mistakes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionStats = `-- name: UpdateQuestionStats :exec
INSERT INTO question_stats (question_id, correct, mistakes)
VALUES ($1, $2, $3)
ON CONFLICT (question_id) DO UPDATE SET
    correct = question_stats.correct + EXCLUDED.correct,
    mistakes = question_stats.mistakes + EXCLUDED.mistakes
`

type UpdateQuestionStatsParams struct {
	QuestionID string
	Correct    int32
	Mistakes   int32
}

func (q *Queries) UpdateQuestionStats(ctx context.Context, arg UpdateQuestionStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestionStats, arg.QuestionID, arg.Correct, arg.Mistakes)
	return err
}
