// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulator_submissions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSimulatorSubmission = `-- name: CreateSimulatorSubmission :one
INSERT INTO simulator_submissions (user_id, simulator_id, challenge_id, code, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, simulator_id, challenge_id, code, status, created_at
`

type CreateSimulatorSubmissionParams struct {
	UserID      uuid.UUID
	SimulatorID string
	ChallengeID string
	Code        string
	Status      string
}

func (q *Queries) CreateSimulatorSubmission(ctx context.Context, arg CreateSimulatorSubmissionParams) (SimulatorSubmission, error) {
	row := q.db.QueryRowContext(ctx, createSimulatorSubmission,
		arg.UserID,
		arg.SimulatorID,
		arg.ChallengeID,
		arg.Code,
		arg.Status,
	)
	var i SimulatorSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SimulatorID,
		&i.ChallengeID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSubmissionsForChallenge = `-- name: DeleteUserSubmissionsForChallenge :exec
DELETE FROM simulator_submissions
WHERE user_id = $1 AND challenge_id = $2
`

type DeleteUserSubmissionsForChallengeParams struct {
	UserID      uuid.UUID
	ChallengeID string
}

func (q *Queries) DeleteUserSubmissionsForChallenge(ctx context.Context, arg DeleteUserSubmissionsForChallengeParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubmissionsForChallenge, arg.UserID, arg.ChallengeID)
	return err
}

const listUserSubmissionsForChallenge = `-- name: ListUserSubmissionsForChallenge :many
SELECT id, user_id, simulator_id, challenge_id, code, status, created_at FROM simulator_submissions
WHERE user_id = $1 AND challenge_id = $2
ORDER BY created_at DESC
`

type ListUserSubmissionsForChallengeParams struct {
	UserID      uuid.UUID
	ChallengeID string
}

func (q *Queries) ListUserSubmissionsForChallenge(ctx context.Context, arg ListUserSubmissionsForChallengeParams) ([]SimulatorSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubmissionsForChallenge, arg.UserID, arg.ChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimulatorSubmission
	for rows.Next() {
		var i SimulatorSubmission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SimulatorID,
			&i.ChallengeID,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
