// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulator_progress.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSimulatorProgress = `-- name: GetSimulatorProgress :one
SELECT user_id, simulator_category, path, is_completed, updated_at FROM simulator_progress
WHERE user_id = $1 AND path = $2
`

type GetSimulatorProgressParams struct {
	UserID uuid.UUID
	Path   string
}

// Get a user's progress for a specific simulator
func (q *Queries) GetSimulatorProgress(ctx context.Context, arg GetSimulatorProgressParams) (SimulatorProgress, error) {
	row := q.db.QueryRowContext(ctx, getSimulatorProgress, arg.UserID, arg.Path)
	var i SimulatorProgress
	err := row.Scan(
		&i.UserID,
		&i.SimulatorCategory,
		&i.Path,
		&i.IsCompleted,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserSimulatorProgress = `-- name: ListUserSimulatorProgress :many
SELECT user_id, simulator_category, path, is_completed, updated_at FROM simulator_progress
WHERE user_id = $1
ORDER BY simulator_category, path
`

// List all simulator progress related to a user, ordered by category
func (q *Queries) ListUserSimulatorProgress(ctx context.Context, userID uuid.UUID) ([]SimulatorProgress, error) {
	rows, err := q.db.QueryContext(ctx, listUserSimulatorProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimulatorProgress
	for rows.Next() {
		var i SimulatorProgress
		if err := rows.Scan(
			&i.UserID,
			&i.SimulatorCategory,
			&i.Path,
			&i.IsCompleted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSimulatorProgressForCategory = `-- name: ListUserSimulatorProgressForCategory :many
SELECT user_id, simulator_category, path, is_completed, updated_at FROM simulator_progress
WHERE user_id = $1 AND simulator_category = $2
`

type ListUserSimulatorProgressForCategoryParams struct {
	UserID            uuid.UUID
	SimulatorCategory string
}

// Get all progress for a specific user and specific category
func (q *Queries) ListUserSimulatorProgressForCategory(ctx context.Context, arg ListUserSimulatorProgressForCategoryParams) ([]SimulatorProgress, error) {
	rows, err := q.db.QueryContext(ctx, listUserSimulatorProgressForCategory, arg.UserID, arg.SimulatorCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimulatorProgress
	for rows.Next() {
		var i SimulatorProgress
		if err := rows.Scan(
			&i.UserID,
			&i.SimulatorCategory,
			&i.Path,
			&i.IsCompleted,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSimulatorProgress = `-- name: UpsertSimulatorProgress :exec
INSERT INTO simulator_progress (user_id, simulator_category, path, is_completed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, path) DO UPDATE
SET 
    is_completed = EXCLUDED.is_completed,
    updated_at = now()
`

type UpsertSimulatorProgressParams struct {
	UserID            uuid.UUID
	SimulatorCategory string
	Path              string
	IsCompleted       bool
}

// Store or update a user's progress for a specific simulator path
func (q *Queries) UpsertSimulatorProgress(ctx context.Context, arg UpsertSimulatorProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertSimulatorProgress,
		arg.UserID,
		arg.SimulatorCategory,
		arg.Path,
		arg.IsCompleted,
	)
	return err
}
