// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulators.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO simulator_challenges (
    id, simulator_id, slug, title, description, order_index, 
    initial_code, program_structure, test_cases, capacity, 
    next_challenge_id, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, simulator_id, slug, title, description, order_index, initial_code, program_structure, test_cases, capacity, next_challenge_id, is_active
`

type CreateChallengeParams struct {
	ID               string
	SimulatorID      string
	Slug             string
	Title            string
	Description      string
	OrderIndex       int32
	InitialCode      sql.NullString
	ProgramStructure json.RawMessage
	TestCases        json.RawMessage
	Capacity         json.RawMessage
	NextChallengeID  sql.NullString
	IsActive         bool
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (SimulatorChallenge, error) {
	row := q.db.QueryRowContext(ctx, createChallenge,
		arg.ID,
		arg.SimulatorID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.InitialCode,
		arg.ProgramStructure,
		arg.TestCases,
		arg.Capacity,
		arg.NextChallengeID,
		arg.IsActive,
	)
	var i SimulatorChallenge
	err := row.Scan(
		&i.ID,
		&i.SimulatorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.InitialCode,
		&i.ProgramStructure,
		&i.TestCases,
		&i.Capacity,
		&i.NextChallengeID,
		&i.IsActive,
	)
	return i, err
}

const createSimulator = `-- name: CreateSimulator :one
INSERT INTO simulators (id, slug, name, description, initial_code, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name, description, is_active, initial_code
`

type CreateSimulatorParams struct {
	ID          string
	Slug        string
	Name        string
	Description string
	InitialCode string
	IsActive    bool
}

func (q *Queries) CreateSimulator(ctx context.Context, arg CreateSimulatorParams) (Simulator, error) {
	row := q.db.QueryRowContext(ctx, createSimulator,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.InitialCode,
		arg.IsActive,
	)
	var i Simulator
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InitialCode,
	)
	return i, err
}

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM simulator_challenges
WHERE id = $1
`

func (q *Queries) DeleteChallenge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChallenge, id)
	return err
}

const deleteSimulatorChallenges = `-- name: DeleteSimulatorChallenges :exec
DELETE FROM simulator_challenges
WHERE simulator_id = $1
`

func (q *Queries) DeleteSimulatorChallenges(ctx context.Context, simulatorID string) error {
	_, err := q.db.ExecContext(ctx, deleteSimulatorChallenges, simulatorID)
	return err
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, simulator_id, slug, title, description, order_index, initial_code, program_structure, test_cases, capacity, next_challenge_id, is_active FROM simulator_challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id string) (SimulatorChallenge, error) {
	row := q.db.QueryRowContext(ctx, getChallengeByID, id)
	var i SimulatorChallenge
	err := row.Scan(
		&i.ID,
		&i.SimulatorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.InitialCode,
		&i.ProgramStructure,
		&i.TestCases,
		&i.Capacity,
		&i.NextChallengeID,
		&i.IsActive,
	)
	return i, err
}

const getChallengeBySlug = `-- name: GetChallengeBySlug :one
SELECT 
    c.id, c.simulator_id, c.slug, c.title, c.description, c.order_index, 
    (s.initial_code || COALESCE(c.initial_code, ''))::TEXT as initial_code,
    c.program_structure, c.test_cases, c.capacity, c.next_challenge_id, c.is_active, 
    next_c.slug as next_challenge_slug
FROM simulator_challenges c
JOIN simulators s ON c.simulator_id = s.id
LEFT JOIN simulator_challenges next_c ON c.next_challenge_id = next_c.id
WHERE c.simulator_id = $1 AND c.slug = $2 AND c.is_active = TRUE
`

type GetChallengeBySlugParams struct {
	SimulatorID string
	Slug        string
}

type GetChallengeBySlugRow struct {
	ID                string
	SimulatorID       string
	Slug              string
	Title             string
	Description       string
	OrderIndex        int32
	InitialCode       string
	ProgramStructure  json.RawMessage
	TestCases         json.RawMessage
	Capacity          json.RawMessage
	NextChallengeID   sql.NullString
	IsActive          bool
	NextChallengeSlug sql.NullString
}

func (q *Queries) GetChallengeBySlug(ctx context.Context, arg GetChallengeBySlugParams) (GetChallengeBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getChallengeBySlug, arg.SimulatorID, arg.Slug)
	var i GetChallengeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.SimulatorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.InitialCode,
		&i.ProgramStructure,
		&i.TestCases,
		&i.Capacity,
		&i.NextChallengeID,
		&i.IsActive,
		&i.NextChallengeSlug,
	)
	return i, err
}

const getNextChallengeByOrder = `-- name: GetNextChallengeByOrder :one
SELECT slug FROM simulator_challenges
WHERE simulator_id = $1 AND order_index > $2 AND is_active = TRUE
ORDER BY order_index ASC
LIMIT 1
`

type GetNextChallengeByOrderParams struct {
	SimulatorID string
	OrderIndex  int32
}

func (q *Queries) GetNextChallengeByOrder(ctx context.Context, arg GetNextChallengeByOrderParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextChallengeByOrder, arg.SimulatorID, arg.OrderIndex)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getSimulatorBySlug = `-- name: GetSimulatorBySlug :one
SELECT id, slug, name, description, is_active, initial_code FROM simulators
WHERE slug = $1 AND is_active = TRUE
`

func (q *Queries) GetSimulatorBySlug(ctx context.Context, slug string) (Simulator, error) {
	row := q.db.QueryRowContext(ctx, getSimulatorBySlug, slug)
	var i Simulator
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InitialCode,
	)
	return i, err
}

const getSimulatorCurriculum = `-- name: GetSimulatorCurriculum :many
SELECT 
    s.id as simulator_id,
    s.slug as simulator_slug,
    s.name as simulator_name,
    s.description as simulator_description,
    s.initial_code as simulator_initial_code,
    s.is_active as simulator_is_active,
    c.id as challenge_id,
    c.slug as challenge_slug,
    c.title as challenge_title,
    c.order_index
FROM simulators s
LEFT JOIN simulator_challenges c ON s.id = c.simulator_id
WHERE s.is_active = TRUE AND (c.is_active = TRUE OR c.is_active IS NULL)
ORDER BY s.name, c.order_index
`

type GetSimulatorCurriculumRow struct {
	SimulatorID          string
	SimulatorSlug        string
	SimulatorName        string
	SimulatorDescription string
	SimulatorInitialCode string
	SimulatorIsActive    bool
	ChallengeID          sql.NullString
	ChallengeSlug        sql.NullString
	ChallengeTitle       sql.NullString
	OrderIndex           sql.NullInt32
}

func (q *Queries) GetSimulatorCurriculum(ctx context.Context) ([]GetSimulatorCurriculumRow, error) {
	rows, err := q.db.QueryContext(ctx, getSimulatorCurriculum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimulatorCurriculumRow
	for rows.Next() {
		var i GetSimulatorCurriculumRow
		if err := rows.Scan(
			&i.SimulatorID,
			&i.SimulatorSlug,
			&i.SimulatorName,
			&i.SimulatorDescription,
			&i.SimulatorInitialCode,
			&i.SimulatorIsActive,
			&i.ChallengeID,
			&i.ChallengeSlug,
			&i.ChallengeTitle,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimulatorCurriculumAdmin = `-- name: GetSimulatorCurriculumAdmin :many
SELECT 
    s.id as simulator_id,
    s.slug as simulator_slug,
    s.name as simulator_name,
    s.description as simulator_description,
    s.initial_code as simulator_initial_code,
    s.is_active as simulator_is_active,
    c.id as challenge_id,
    c.slug as challenge_slug,
    c.title as challenge_title,
    c.order_index
FROM simulators s
LEFT JOIN simulator_challenges c ON s.id = c.simulator_id
ORDER BY s.name, c.order_index
`

type GetSimulatorCurriculumAdminRow struct {
	SimulatorID          string
	SimulatorSlug        string
	SimulatorName        string
	SimulatorDescription string
	SimulatorInitialCode string
	SimulatorIsActive    bool
	ChallengeID          sql.NullString
	ChallengeSlug        sql.NullString
	ChallengeTitle       sql.NullString
	OrderIndex           sql.NullInt32
}

func (q *Queries) GetSimulatorCurriculumAdmin(ctx context.Context) ([]GetSimulatorCurriculumAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, getSimulatorCurriculumAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimulatorCurriculumAdminRow
	for rows.Next() {
		var i GetSimulatorCurriculumAdminRow
		if err := rows.Scan(
			&i.SimulatorID,
			&i.SimulatorSlug,
			&i.SimulatorName,
			&i.SimulatorDescription,
			&i.SimulatorInitialCode,
			&i.SimulatorIsActive,
			&i.ChallengeID,
			&i.ChallengeSlug,
			&i.ChallengeTitle,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengesForSimulator = `-- name: ListChallengesForSimulator :many
SELECT id, simulator_id, slug, title, description, order_index, initial_code, program_structure, test_cases, capacity, next_challenge_id, is_active FROM simulator_challenges
WHERE simulator_id = $1 AND is_active = TRUE
ORDER BY order_index ASC
`

func (q *Queries) ListChallengesForSimulator(ctx context.Context, simulatorID string) ([]SimulatorChallenge, error) {
	rows, err := q.db.QueryContext(ctx, listChallengesForSimulator, simulatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimulatorChallenge
	for rows.Next() {
		var i SimulatorChallenge
		if err := rows.Scan(
			&i.ID,
			&i.SimulatorID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.InitialCode,
			&i.ProgramStructure,
			&i.TestCases,
			&i.Capacity,
			&i.NextChallengeID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulators = `-- name: ListSimulators :many
SELECT id, slug, name, description, is_active, initial_code FROM simulators
WHERE is_active = TRUE
`

func (q *Queries) ListSimulators(ctx context.Context) ([]Simulator, error) {
	rows, err := q.db.QueryContext(ctx, listSimulators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Simulator
	for rows.Next() {
		var i Simulator
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.InitialCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChallenge = `-- name: UpdateChallenge :one
UPDATE simulator_challenges
SET 
    slug = $2, 
    title = $3, 
    description = $4, 
    order_index = $5, 
    initial_code = $6, 
    program_structure = $7, 
    test_cases = $8, 
    capacity = $9, 
    next_challenge_id = $10, 
    is_active = $11
WHERE id = $1
RETURNING id, simulator_id, slug, title, description, order_index, initial_code, program_structure, test_cases, capacity, next_challenge_id, is_active
`

type UpdateChallengeParams struct {
	ID               string
	Slug             string
	Title            string
	Description      string
	OrderIndex       int32
	InitialCode      sql.NullString
	ProgramStructure json.RawMessage
	TestCases        json.RawMessage
	Capacity         json.RawMessage
	NextChallengeID  sql.NullString
	IsActive         bool
}

func (q *Queries) UpdateChallenge(ctx context.Context, arg UpdateChallengeParams) (SimulatorChallenge, error) {
	row := q.db.QueryRowContext(ctx, updateChallenge,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.InitialCode,
		arg.ProgramStructure,
		arg.TestCases,
		arg.Capacity,
		arg.NextChallengeID,
		arg.IsActive,
	)
	var i SimulatorChallenge
	err := row.Scan(
		&i.ID,
		&i.SimulatorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.InitialCode,
		&i.ProgramStructure,
		&i.TestCases,
		&i.Capacity,
		&i.NextChallengeID,
		&i.IsActive,
	)
	return i, err
}

const updateSimulator = `-- name: UpdateSimulator :one
UPDATE simulators
SET name = $2, slug = $3, description = $4, initial_code = $5, is_active = $6
WHERE id = $1
RETURNING id, slug, name, description, is_active, initial_code
`

type UpdateSimulatorParams struct {
	ID          string
	Name        string
	Slug        string
	Description string
	InitialCode string
	IsActive    bool
}

func (q *Queries) UpdateSimulator(ctx context.Context, arg UpdateSimulatorParams) (Simulator, error) {
	row := q.db.QueryRowContext(ctx, updateSimulator,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.InitialCode,
		arg.IsActive,
	)
	var i Simulator
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.InitialCode,
	)
	return i, err
}
