// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    clerk_id,
    course_id,
    first_name,
    middle_name,
    last_name,
    block_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, clerk_id, course_id, first_name, middle_name, last_name, created_at, updated_at, block_id
`

type CreateUserParams struct {
	ClerkID    string
	CourseID   uuid.NullUUID
	FirstName  sql.NullString
	MiddleName sql.NullString
	LastName   sql.NullString
	BlockID    sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ClerkID,
		arg.CourseID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.BlockID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.ClerkID,
		&i.CourseID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockID,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, clerk_id, course_id, first_name, middle_name, last_name, created_at, updated_at, block_id from users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.ClerkID,
			&i.CourseID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersByCourse = `-- name: GetAllUsersByCourse :many
SELECT user_id, clerk_id, course_id, first_name, middle_name, last_name, created_at, updated_at, block_id from users
WHERE course_id = $1
`

func (q *Queries) GetAllUsersByCourse(ctx context.Context, courseID uuid.NullUUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.ClerkID,
			&i.CourseID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByClearkID = `-- name: GetUserByClearkID :one
SELECT user_id, clerk_id, course_id, first_name, middle_name, last_name, created_at, updated_at, block_id from users
WHERE clerk_id = $1 LIMIT 1
`

func (q *Queries) GetUserByClearkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByClearkID, clerkID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.ClerkID,
		&i.CourseID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, clerk_id, course_id, first_name, middle_name, last_name, created_at, updated_at, block_id from users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.ClerkID,
		&i.CourseID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    course_id = COALESCE($1, course_id),
    first_name = COALESCE($2, first_name),
    middle_name = COALESCE($3, middle_name),
    last_name = COALESCE($4, last_name),
    block_id = COALESCE($5, block_id),
    updated_at = now()
WHERE clerk_id = $6
RETURNING user_id, clerk_id, course_id, first_name, middle_name, last_name, created_at, updated_at, block_id
`

type UpdateUserParams struct {
	CourseID   uuid.NullUUID
	FirstName  sql.NullString
	MiddleName sql.NullString
	LastName   sql.NullString
	BlockID    sql.NullString
	ClerkID    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.CourseID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.BlockID,
		arg.ClerkID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.ClerkID,
		&i.CourseID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockID,
	)
	return i, err
}
