### mark lesson progress 1
POST http://localhost:8080/api/progress/sample_lesson_category/lesson_1 HTTP/1.1

### mark lesson progress 2
POST http://localhost:8080/api/progress/sample_lesson_category/lesson_2 HTTP/1.1

### get lesson progress
GET http://localhost:8080/api/progress HTTP/1.1