### mark/mark lesson progress 1
POST http://localhost:8080/api/progress/sample_lesson_category/lesson_1 HTTP/1.1

### mark/create lesson progress 2
POST http://localhost:8080/api/progress/sample_lesson_category/lesson_2 HTTP/1.1

### get all lesson progress
GET http://localhost:8080/api/progress HTTP/1.1

### get one specific progress status
GET http://localhost:8080/api/progress/sample_lesson_category/lesson_1 HTTP/1.1

### unmark/delete lesson progress 1
DELETE http://localhost:8080/api/progress/sample_lesson_category/lesson_1 HTTP/1.1

### delete all lesson progress
DELETE http://localhost:8080/api/progress HTTP/1.1
